# Generated by Django 4.2.2 on 2023-06-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="creat_time",
            field=models.DateField(verbose_name="入职时间"),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app01.department",
                verbose_name="部门",
            ),
        ),
    ]
