# Generated by Django 4.2.2 on 2023-06-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0003_prettynum"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Department",
            new_name="AImodel",
        ),
    ]
