# Generated by Django 4.2.2 on 2023-06-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0004_rename_department_aimodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="account",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="age",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="creat_time",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="depart",
        ),
        migrations.RemoveField(
            model_name="userinfo",
            name="gender",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="邮箱"
            ),
        ),
    ]
