# Generated by Django 4.2.2 on 2023-06-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app01", "0005_remove_userinfo_account_remove_userinfo_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pnum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=11, verbose_name="号码")),
                ("price", models.IntegerField(verbose_name="价格")),
                (
                    "level",
                    models.SmallIntegerField(
                        choices=[(1, "1级"), (2, "2级"), (3, "3级"), (4, "4级")],
                        default=1,
                        verbose_name="级别",
                    ),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(1, "已占用"), (2, "未占用")], default=2, verbose_name="状态"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="PrettyNum",
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="password",
            field=models.TextField(max_length=64, verbose_name="密码"),
        ),
    ]
